version: '3'

services:
  app:
    image: u_login_in_dickerhub/u_imagen_ame:latest
    env_file:
      - .env.prod
    ports:
      - '4000:4000'
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres
    env_file:
      - .env.db
    ports:
      - '5432:5432'
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    env_file:
      - .env.pgadmin
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env.minio
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    command: server ./data --console-address ":9001"
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
